#!/bin/bash
#
# SO 2013 - FASE 1 
#
# GRUPO so007
# 39295 Diogo Marques
#
# mkimage

if [ $# -eq 1 ] 
	then
		dd if=/dev/urandom of=temp bs=1 count=$1 > /dev/null 2>&1
		strings temp
		rm temp
	else
		echo "Este script $0 precisa de um unico argumento"
fi