#!/bin/bash
#
# SO 2013 - FASE 1 
#
# GRUPO so007
# 39295 Diogo Marques
#
# vsslr

logdir=

for i in `ls logs/ | grep log.gz`
do
	if [ `echo $i | awk -F. '{print $(NF-2)}'` -ge $1 ]
	then	
		rm logs/$i
	fi
	mv logs/$i logs/$i | awk -F. ' OFS="." {$(NF-2)=$(NF-2)+1; print $0}'
done